import type { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "React Native Tips",
    description: "Learn some useful tips for React Native development.",
    image: "https://source.unsplash.com/random/300x200?react",
    url: "https://example.com/blog/react-native-tips",
    date: "2026-02-20",
    tags: ["React Native", "Tips"],
  },
  {
    id: "2",
    title: "Expo vs React Native CLI",
    description: "A comparison between Expo and React Native CLI.",
    image: "https://source.unsplash.com/random/300x200?expo",
    url: "https://example.com/blog/expo-vs-cli",
    date: "2026-02-18",
    tags: ["Expo", "React Native"],
  },
  {
    id: "3",
    title: "Styling in React Native",
    description: "Best practices for styling your React Native apps.",
    image: "https://source.unsplash.com/random/300x200?style",
    url: "https://example.com/blog/styling-react-native",
    date: "2026-02-15",
    tags: ["Styling", "React Native"],
  },
  {
    id: "4",
    title: "Performance Optimization",
    description: "How to optimize performance in React Native.",
    image: "https://source.unsplash.com/random/300x200?performance",
    url: "https://example.com/blog/performance-optimization",
    date: "2026-02-10",
    tags: ["Performance", "React Native"],
  },
  {
    id: "5",
    title: "Navigation Patterns",
    description: "Explore navigation patterns in React Native apps.",
    image: "https://source.unsplash.com/random/300x200?navigation",
    url: "https://example.com/blog/navigation-patterns",
    date: "2026-02-05",
    tags: ["Navigation", "React Native"],
  },
  {
    id: "6",
    title: "Testing Strategies",
    description: "Effective testing strategies for React Native.",
    image: "https://source.unsplash.com/random/300x200?testing",
    url: "https://example.com/blog/testing-strategies",
    date: "2026-01-30",
    tags: ["Testing", "React Native"],
  },
  {
    id: "7",
    title: "Animations in React Native",
    description: "Create beautiful animations in React Native.",
    image: "https://source.unsplash.com/random/300x200?animation",
    url: "https://example.com/blog/animations",
    date: "2026-01-25",
    tags: ["Animation", "React Native"],
  },
  {
    id: "8",
    title: "Using TypeScript",
    description: "Benefits of using TypeScript in React Native.",
    image: "https://source.unsplash.com/random/300x200?typescript",
    url: "https://example.com/blog/typescript",
    date: "2026-01-20",
    tags: ["TypeScript", "React Native"],
  },
  {
    id: "9",
    title: "Debugging Techniques",
    description: "Debugging React Native apps efficiently.",
    image: "https://source.unsplash.com/random/300x200?debug",
    url: "https://example.com/blog/debugging",
    date: "2026-01-15",
    tags: ["Debugging", "React Native"],
  },
  {
    id: "10",
    title: "Deploying to App Stores",
    description: "How to deploy your app to the App Store and Google Play.",
    image: "https://source.unsplash.com/random/300x200?deploy",
    url: "https://example.com/blog/deploying",
    date: "2026-01-10",
    tags: ["Deployment", "React Native"],
  },
  {
    id: "11",
    title: "State Management",
    description: "Choosing the right state management solution.",
    image: "https://source.unsplash.com/random/300x200?state",
    url: "https://example.com/blog/state-management",
    date: "2026-01-05",
    tags: ["State", "React Native"],
  },
  {
    id: "12",
    title: "Accessibility in Apps",
    description: "Making your React Native apps accessible.",
    image: "https://source.unsplash.com/random/300x200?accessibility",
    url: "https://example.com/blog/accessibility",
    date: "2026-01-01",
    tags: ["Accessibility", "React Native"],
  },
];
